### ISSUE TITLE
🔒 Enhance security practices and add audit logging

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ivyleavedtoadflax/remote.py#54]
## Problem
The current codebase lacks comprehensive security practices that could lead to credential exposure and unauthorized actions:

### Current Security Issues:
1. **Credential exposure risk**: AWS credentials could be logged or exposed in error messages
2. **No input sanitization**: User inputs aren't properly validated before use in commands
3. **Subprocess security**: SSH command construction vulnerable to injection attacks
4. **Sensitive data in logs**: Instance information and potentially sensitive data in debug output
5. **No audit trail**: Limited logging of destructive operations (terminate, delete, etc.)
6. **Missing security linting**: No automated security vulnerability scanning

### Examples of Vulnerabilities:
```python
# Potential command injection vulnerability
def connect_to_instance(instance_name, user_input):
    # If user_input contains shell metacharacters, this could be dangerous
    command = f"ssh -i ~/.ssh/key.pem {user_input}@{instance_name}"
    subprocess.run(command, shell=True)  # DANGEROUS

# Potential credential exposure
def debug_aws_error(error):
    logger.debug(f"AWS Error: {error}")  # May contain credentials
```

## Impact
- **Credential compromise**: Risk of exposing AWS access keys in logs or error messages
- **Command injection**: Malicious input could execute arbitrary commands
- **Compliance issues**: No audit trail for security-critical operations
- **Data leakage**: Sensitive instance information in logs
- **Supply chain risks**: No scanning for vulnerable dependencies

### Phase 1: Input Validation and Sanitization
- [ ] Add input validation for all user-provided data
- [ ] Implement command parameter sanitization
- [ ] Use parameterized subprocess calls instead of shell command construction
- [ ] Add input length limits and format validation

### Phase 2: Credential Protection
- [ ] Implement credential masking in all logging
- [ ] Add AWS credential validation and scope checking
- [ ] Ensure error messages don't expose sensitive information
- [ ] Add credential rotation recommendations

### Phase 3: Audit Logging
- [ ] Implement structured audit logging for all destructive operations
- [ ] Log user actions with timestamps and context
- [ ] Add operation success/failure tracking
- [ ] Include IP address and user identification where possible

### Phase 4: Security Scanning and Monitoring
- [ ] Add security linting to CI pipeline (bandit, safety)
- [ ] Implement dependency vulnerability scanning
- [ ] Add pre-commit security hooks
- [ ] Monitor for suspicious usage patterns

### Input Validation:
```python
import re
from typing import Union

def validate_instance_name(name: str) -> str:
    \"\"\"Validate instance name format and prevent injection.\"\"\"
    if not name or len(name) > 255:
        raise ValueError(\"Instance name must be 1-255 characters\")
    
    # Only allow alphanumeric, hyphens, underscores
    if not re.match(r'^[a-zA-Z0-9_-]+$', name):
        raise ValueError(\"Instance name contains invalid characters\")
    
    return name

def validate_user_input(user_input: str, max_length: int = 100) -> str:
    \"\"\"Sanitize user input to prevent injection attacks.\"\"\"
    if len(user_input) > max_length:
        raise ValueError(f\"Input too long (max {max_length} characters)\")
    
    # Remove or escape potentially dangerous characters
    dangerous_chars = ['`', '$', '|', ';', '&', '>', '<', '(', ')', '{', '}']
    for char in dangerous_chars:
        if char in user_input:
            raise ValueError(f\"Input contains dangerous character: {char}\")
    
    return user_input
```

### Secure Command Execution:
```python
import subprocess
from typing import List

def secure_ssh_command(host: str, username: str, key_path: str, command: str = None) -> subprocess.CompletedProcess:
    \"\"\"Execute SSH command securely using parameterized arguments.\"\"\"
    # Validate inputs
    host = validate_instance_name(host)
    username = validate_user_input(username, max_length=50)
    
    # Use list of arguments instead of shell command string
    ssh_args = [
        'ssh',
        '-i', key_path,
        '-o', 'StrictHostKeyChecking=yes',
        '-o', 'UserKnownHostsFile=~/.ssh/known_hosts',
        f'{username}@{host}'
    ]
    
    if command:
        command = validate_user_input(command, max_length=200)
        ssh_args.append(command)
    
    # Use shell=False for security
    return subprocess.run(ssh_args, shell=False, capture_output=True, text=True)
```

### Credential Masking:
```python
import re
import logging

class SecureFormatter(logging.Formatter):
    \"\"\"Logging formatter that masks sensitive information.\"\"\"
    
    SENSITIVE_PATTERNS = [
        r'(aws_access_key_id[\"\\']?\\s*[:=]\\s*[\"\\']?)([A-Z0-9]{20})([\"\\']?)',
        r'(aws_secret_access_key[\"\\']?\\s*[:=]\\s*[\"\\']?)([A-Za-z0-9/+=]{40})([\"\\']?)',
        r'(password[\"\\']?\\s*[:=]\\s*[\"\\']?)([^\"\\s]+)([\"\\']?)',
        r'(token[\"\\']?\\s*[:=]\\s*[\"\\']?)([A-Za-z0-9/+=]{20,})([\"\\']?)',
    ]
    
    def format(self, record):
        message = super().format(record)
        
        for pattern in self.SENSITIVE_PATTERNS:
            message = re.sub(pattern, r'\\1***REDACTED***\\3', message, flags=re.IGNORECASE)
        
        return message

# Configure secure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(SecureFormatter())
logger.addHandler(handler)
```

### Audit Logging:
```python
import json
from datetime import datetime
from enum import Enum

class AuditEventType(Enum):
    INSTANCE_TERMINATE = \"instance_terminate\"
    INSTANCE_START = \"instance_start\"
    INSTANCE_STOP = \"instance_stop\"
    AMI_CREATE = \"ami_create\"
    VOLUME_DELETE = \"volume_delete\"

class AuditLogger:
    def __init__(self, log_file: str = \"/var/log/remotepy/audit.log\"):
        self.logger = logging.getLogger(\"remotepy.audit\")
        handler = logging.FileHandler(log_file)
        handler.setFormatter(logging.Formatter('%(asctime)s %(message)s'))
        self.logger.addHandler(handler)
        self.logger.setLevel(logging.INFO)
    
    def log_action(self, event_type: AuditEventType, resource_id: str, 
                   success: bool, user: str = None, details: dict = None):
        \"\"\"Log security-relevant actions.\"\"\"
        audit_record = {
            \"timestamp\": datetime.utcnow().isoformat(),
            \"event_type\": event_type.value,
            \"resource_id\": resource_id,
            \"success\": success,
            \"user\": user or \"unknown\",
            \"details\": details or {}
        }
        
        self.logger.info(json.dumps(audit_record))

# Usage example
audit_logger = AuditLogger()

def terminate_instance(instance_id: str):
    try:
        # Perform termination
        ec2_client.terminate_instances(InstanceIds=[instance_id])
        audit_logger.log_action(
            AuditEventType.INSTANCE_TERMINATE,
            instance_id,
            success=True,
            details={\"method\": \"cli\"}
        )
    except Exception as e:
        audit_logger.log_action(
            AuditEventType.INSTANCE_TERMINATE,
            instance_id,
            success=False,
            details={\"error\": str(e)}
        )
        raise
```

### CI/CD Security Pipeline:
```yaml
# .github/workflows/security.yml
name: Security Scanning

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Bandit Security Linter
      run: |
        pip install bandit[toml]
        bandit -r remotepy/ -f json -o bandit-report.json
    
    - name: Run Safety Dependency Check
      run: |
        pip install safety
        safety check --json --output safety-report.json
    
    - name: Run Semgrep Security Analysis
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
```

### Pre-commit Security Hooks:
```yaml
# .pre-commit-config.yaml additions
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
  
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
```

## Acceptance Criteria
- [ ] All user inputs are validated and sanitized
- [ ] Subprocess calls use parameterized arguments (no shell=True)
- [ ] All logging masks sensitive information
- [ ] Audit logging for all destructive operations
- [ ] Security scanning integrated into CI pipeline
- [ ] Pre-commit security hooks prevent credential commits
- [ ] Error messages don't expose sensitive information
- [ ] Documentation on security best practices

## Priority
🟠 **High** - Security issues should be addressed promptly

## Compliance Benefits
- Better audit trail for compliance requirements
- Reduced risk of credential exposure
- Protection against command injection attacks
- Automated security vulnerability detection
- Clear security policies and procedures

## Testing Strategy
- Add security-focused test cases
- Test input validation edge cases
- Verify credential masking in logs
- Test audit logging functionality
- Penetration testing for command injection
